courses/urls.py
from django.conf.urls import url

from .views import (
    CourseList,
    CourseDetail,
    CourseCreation,
    CourseUpdate,
    CourseDelete
)

urlpatterns = [

    url(r'^$', CourseList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', CourseDetail.as_view(), name='detail'),
    url(r'^nuevo$', CourseCreation.as_view(), name='new'),
    url(r'^editar/(?P<pk>\d+)$', CourseUpdate.as_view(), name='edit'),
    url(r'^borrar/(?P<pk>\d+)$', CourseDelete.as_view(), name='delete'),

]

platzi/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^cursos/', include('courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
]

courses/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=140)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    picture = models.ImageField(upload_to='media/courses/pictures', blank=True, null=True)

courses/views.py
from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Course


class CourseList(ListView):
    model = Course


class CourseDetail(DetailView):
    model = Course


class CourseCreation(CreateView):
    model = Course
    success_url = reverse_lazy('courses:list')
    fields = ['name', 'start_date', 'end_date', 'picture']


class CourseUpdate(UpdateView):
    model = Course
    success_url = reverse_lazy('courses:list')
    fields = ['name', 'start_date', 'end_date', 'picture']


class CourseDelete(DeleteView):
    model = Course
    success_url = reverse_lazy('courses:list')

courses/templates/courses/course_confirm_delete.html
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
    <input type="submit" value="Submit" />
</form>

courses/templates/courses/course_detail.html
<h1>{{ course.name }}</h1>
<p>Fecha de inicio: <i>{{ course.start_date }}</i></p>
<p>Fecha de fin: <i>{{ course.end_date }}</i></p>
<p>
    <a href="{% url "courses:list" %}">Regresar</a>
</p>

courses/templates/courses/course_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

courses/templates/courses/course_list.html
<h1>Cursos de Platzi</h1>

<p>
    <a href="{% url "courses:new" %}">Agregar curso</a>
</p>

<ul>
    {% for course in object_list %}
        <li>
            <p>{{ course.name }}</p>
            <p>
                <a href="{% url "courses:detail" course.id %}">Ver</a> | 
                <a href="{% url "courses:edit" course.id %}">Editar</a> | 
                <a href="{% url "courses:delete" course.id %}">Borrar</a> 
            </p>
        </li>
    {% endfor %}
</ul>